# Markdown
This is a markdown cell where we write instructions and math formulas. **Double click** to edit and **press Run** to see the formatted texts.

# Load and Save Notebook
To load a note book, just go to "File" and navigate to "Open...". Use keyboard shortcut **Cmd/Ctrl+s** to save the file. You will be saving a checkpoint as well if you use this keyboard shortcut. You can click on "File" on the menu bar and select an option to revert to a certain checkpoint. Jupyter Notebook will also autosave your file every 120s, but it's still a good practice to press **Cmd/Ctrl+s** often when you write programs. 

# Code Blocks
Below will be an example of a Python code block. Hit **Run** to run the block.

In [1]:
print("Hello world!")

Hello world!


You can also hit **Run All** in "Cell" menu. To run every blocks. 

In [2]:
print("Hello world, again!")

Hello world, again!


# Python Programming
We have finished Jupyter Notebook introduction. Below we will start Python Programming.

## Importing Libraries
For the lab, we will be using different libraries. This is how you do it in Python.

In [3]:
import pandas as pd
import numpy as np

By importing pandas as pd, you can use the shorthand `pd` when you need to use pandas. The same method applies to `np`.

## NumPy Tutorial
Below we show you a few ways to create arrays.

In [4]:
# Create a basic array
x = np.array([0, 1, 2, 3])
print("x:\n", x)

# Create a 2D array
y = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])
print("y:\n", y)

# Create a 3 by 4 empty array
z = np.zeros((3, 4))
print("z:\n", z)

# Create a 5 by 5 array filled with 1s
a = np.ones((5, 5))
print("a:\n", a)

# Create a sequence of numbers, note the array does not include 20
b = np.arange(0, 20, 2)
print("b:\n", b)

# Use reshape to change the dimention of the array
c = np.arange(0, 20, 2, dtype=float).reshape(2, 5)
print("c:\n", c)

# Create a random 6 by 3 array with value between [0, 1).
d = np.random.rand(6, 3)
print("d:\n", d)
    
    # This creates random values ranging between [1, 4).
d = d*3 + 1
print("New d:\n", d)

# Operations
e = d + 10
print("e:\n", e)

x:
 [0 1 2 3]
y:
 [[0 1 2 3]
 [4 5 6 7]]
z:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
a:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
b:
 [ 0  2  4  6  8 10 12 14 16 18]
c:
 [[ 0.  2.  4.  6.  8.]
 [10. 12. 14. 16. 18.]]
d:
 [[6.59681392e-01 8.96677795e-01 2.17912846e-03]
 [7.90756753e-01 2.59040417e-01 5.48399450e-01]
 [9.97123735e-01 1.40840666e-01 1.24249752e-01]
 [8.20323674e-04 8.49620963e-01 3.84546443e-01]
 [9.25738074e-02 1.34694616e-01 5.66398716e-01]
 [2.75715157e-01 8.26801499e-01 6.55253480e-01]]
New d:
 [[2.97904418 3.69003338 1.00653739]
 [3.37227026 1.77712125 2.64519835]
 [3.99137121 1.422522   1.37274925]
 [1.00246097 3.54886289 2.15363933]
 [1.27772142 1.40408385 2.69919615]
 [1.82714547 3.4804045  2.96576044]]
e:
 [[12.97904418 13.69003338 11.00653739]
 [13.37227026 11.77712125 12.64519835]
 [13.99137121 11.422522   11.37274925]
 [11.00246097 13.54886289 12.15363933]
 [11.27772142 11.40408385 12.69919615]
 [11.82714

**Now it's your turn.** 

**To-do:**
1. Create and print out an empty array with dimensions of 15 by 29.
2. From the 0 array you created, make it to an ones array without using np.ones. Print out the array.
3. Create an 8 by 9 array with values between $[5, 11)$. Note that 11 is excluded. Print out the array.



In [5]:
### Insert code below ###


zero_array = np.zeros((15,29))
print(zero_array)
ones_array = zero_array + 1
print(ones_array)
range_array = np.arange(5,11)
print(range_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0

## Pandas Tutorial
### Create Data Frame
Pandas is a data frame that will be used to handel our data.

In [6]:
# Create a data frame from numpy array
df_1 = pd.DataFrame(y, columns=['col 1', 'col 2', 'col 3', 'col 4'])
print("df_1:\n", df_1, '\n')
print("------------------------------------") # for readability only

# You can also use display() to make the dataframe looks nicer at the output
print("df_1 using display:")
display(df_1)
print("------------------------------------")

# Create a data frame with strings
data_2 = {'Aminal': ['Dog', 'Cat'], 'Color': ['Yellow', 'Pink'], 'Age': [1, 3]}
df_2 = pd.DataFrame(data=data_2)
print("df_2:\n", df_2, '\n')
print("------------------------------------")

# Print the type of the data. Notice that Age is int
df_2.dtypes

df_1:
    col 1  col 2  col 3  col 4
0      0      1      2      3
1      4      5      6      7 

------------------------------------
df_1 using display:


col 1  col 2  col 3  col 4
0      0      1      2      3
1      4      5      6      7

------------------------------------
df_2:
   Aminal   Color  Age
0    Dog  Yellow    1
1    Cat    Pink    3 

------------------------------------


Aminal    object
Color     object
Age        int64
dtype: object

#### Now it's your turn. 

**To-do:**

1. Create a data frame containing demographics of you and your 2 friends. The data frame should be 3 by 4. The columns will be 'Name', 'Age', 'Height', 'Hobby'. You can make up data if you like. Print or display the result. 

In [7]:
### Insert your code below ###


demographics = pd.DataFrame(data = {"Name": ["Nick", "Adam", "Bob"], 
                                    "Age": [39, 38, 40], 
                                    "Height": [69, 70, 68], 
                                    "Hobby": ["programming", "photography", "birdwatching"]})
display(demographics)

Name  Age  Height         Hobby
0  Nick   39      69   programming
1  Adam   38      70   photography
2   Bob   40      68  birdwatching

### Modify Data Frame
Notice that when you use `=`, you are not copying data frame. You are just saying that `df_3` is now referring to the same data frame as `df_1`. If you change values in `df_3` you will change the values in `df_1` too, since both are referring to the same dataframe. Also notice that every time you click **Run** in this block, the values in `'col 1'` changes.  

In [8]:
# Add a new column
df_2['Weight'] = [89, 60]
print("New df_2:")
display(df_2)
print("------------------------------------")

# Special thing to take notice
df_3 = df_1
df_3['col 1'] = df_3['col 1'] - 1
print("df_3:")
display(df_3)
print("df_1:")
display(df_1)


New df_2:


Aminal   Color  Age  Weight
0    Dog  Yellow    1      89
1    Cat    Pink    3      60

------------------------------------
df_3:


col 1  col 2  col 3  col 4
0     -1      1      2      3
1      3      5      6      7

df_1:


col 1  col 2  col 3  col 4
0     -1      1      2      3
1      3      5      6      7

### Print Specific Data
Here we use `.loc`, `.at` to obtain the cell values by providing the **labels** (e.g. 'Age', 'Weight'). For rows, since we do not create labels for them the defaults will be 0, 1, 2, 3...etc. We use `.iloc`, `.iat` to obtain the cell values by prividing the indicies (positions) of the rows and columns. 

In [9]:
# Few ways to view the values

# Create a data frame based on data_2; the values are copied
df_4 = pd.DataFrame(data=data_2)
print("df_4:")
display(df_4)
print("------------------------------------")

# Selection by Label
    # Getting the scalar value
dog_age = df_4.loc[0, 'Age']
print("Age of Dog:", dog_age, '\n')
print("------------------------------------")

    # Getting the whole column 
aminals_age = df_4.loc[:, ['Age']]
print("Age Column:")
display(aminals_age)
print("------------------------------------")

    # Faster way to get a scalar
cat_age = df_4.at[1, 'Age']
print("Age of Cat:", cat_age, '\n')
print("------------------------------------")

# Selection by position
    # Selecting Row based on row number
dog = df_4.iloc[0]
print("Dog row:")
print(dog, '\n')
print("------------------------------------")

    # Selecting Col based on col number
animals_age_p = df_4.iloc[:, 2]
print("Animals' age:")
print(animals_age_p, '\n')
print("------------------------------------")
    # Selecting cell based on col number
cat_age_p = df_4.iat[1, 2]
print("Age of Cat: ", cat_age_p)

df_4:


Aminal   Color  Age
0    Dog  Yellow    1
1    Cat    Pink    3

------------------------------------
Age of Dog: 1 

------------------------------------
Age Column:


Age
0    1
1    3

------------------------------------
Age of Cat: 3 

------------------------------------
Dog row:
Aminal       Dog
Color     Yellow
Age            1
Name: 0, dtype: object 

------------------------------------
Animals' age:
0    1
1    3
Name: Age, dtype: int64 

------------------------------------
Age of Cat:  3


#### Now it's your turn.
**To-do:**

1. Add a new **row** to your **demographics** data frame. The new row will contain information of another friend. *Note that we haven't taught you how to do so but you should be able to find resources online easily.* Print/display the data frame.
2. Print all the information (whole row) about you using `.loc`.
3. Print the 'Name' of your second friend using `.iat`.


In [10]:
### Insert your code below ###


demographics = demographics.append({"Name": "Charles", "Age": 37, "Height": 80, "Hobby": "gaming"}, ignore_index=True)
display(demographics)
display(demographics.loc[0])
print(demographics.iat[1,0])

Name  Age  Height         Hobby
0     Nick   39      69   programming
1     Adam   38      70   photography
2      Bob   40      68  birdwatching
3  Charles   37      80        gaming

Name             Nick
Age                39
Height             69
Hobby     programming
Name: 0, dtype: object

Adam


**Congradulation on finishing the tutorial! Now you can move on to the next step of the lab.**